showGrid: false

url: http://blog.whitepeaksoftware.com
title: White Peak Software Blog
author: Kirby Turner

root: /

paginate: 10          # Posts per page on the blog index
recent_posts: 5       # Posts in the sidebar Recent Posts section

permalink: /:year/:month/:day/:title/

# Twitter
twitter_user: whitepeak
twitter_tweet_count: 4
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true


# Category plugin (https://github.com/recurser/jekyll-plugins)
category_dir: category
